/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About/About.vue')['default']
    Main: typeof import('./src/components/Main/Main.vue')['default']
    ProjectItem: typeof import('./src/components/ProjectItem/ProjectItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader/SectionHeader.vue')['default']
    SkillBlock: typeof import('./src/components/SkillBlock/SkillBlock.vue')['default']
    Skills: typeof import('./src/components/Skills/Skills.vue')['default']
    SkillsBlock: typeof import('./src/components/SkillBlock/SkillsBlock.vue')['default']
  }
}
